// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Publicacion.Infrastructure.Persistence;

#nullable disable

namespace Publicacion.Infrastructure.Migrations
{
    [DbContext(typeof(PublicationContext))]
    [Migration("20251201034618_AddImageToPublication")]
    partial class AddImageToPublication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Publicacion.Domain.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PublicationId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("PublicationId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Publicacion.Domain.Entities.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("LocationCoordinates")
                        .HasColumnType("text");

                    b.Property<int>("M2")
                        .HasColumnType("integer");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Rooms")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Publications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 15,
                            Description = "Casa con jardin y pileta, ideal para familia.",
                            LocationCoordinates = "-34.57073690807198, -58.41713926905615",
                            M2 = 140,
                            OperationType = "Venta",
                            PropertyType = "Casa",
                            Rooms = 4
                        },
                        new
                        {
                            Id = 2,
                            Age = 20,
                            Description = "Departamento de dos ambientes en Villa Crespo",
                            LocationCoordinates = "-34.5912740626822, -58.44926342405723",
                            M2 = 35,
                            OperationType = "Alquiler",
                            PropertyType = "Departamento",
                            Rooms = 2
                        },
                        new
                        {
                            Id = 3,
                            Age = 10,
                            Description = "Hermosa casa familiar con jardín amplio.",
                            LocationCoordinates = "-34.545388102550206, -58.44912493444169",
                            M2 = 250,
                            OperationType = "Venta",
                            PropertyType = "Casa",
                            Rooms = 5
                        },
                        new
                        {
                            Id = 4,
                            Age = 0,
                            Description = "Terreno de 800m2 en zona de alto crecimiento, listo para construir.",
                            LocationCoordinates = "-33.15161855419031, -68.89191390749127",
                            M2 = 800,
                            OperationType = "Venta",
                            PropertyType = "Terreno",
                            Rooms = 0
                        },
                        new
                        {
                            Id = 5,
                            Age = 5,
                            Description = "Oficina moderna en Microcentro, ideal para 5 puestos de trabajo.",
                            LocationCoordinates = "-34.60792311626675, -58.36964480190205",
                            M2 = 65,
                            OperationType = "Alquiler",
                            PropertyType = "Oficina",
                            Rooms = 3
                        },
                        new
                        {
                            Id = 6,
                            Age = 2,
                            Description = "Monoambiente en Palermo, con balcón y amenities de lujo.",
                            LocationCoordinates = "-34.57966563810134, -58.42070739762831",
                            M2 = 45,
                            OperationType = "Venta",
                            PropertyType = "Departamento",
                            Rooms = 1
                        },
                        new
                        {
                            Id = 7,
                            Age = 25,
                            Description = "Casa estilo rústico en las afueras, con mucha tranquilidad.",
                            LocationCoordinates = "-34.47886239795676, -58.530800851190776",
                            M2 = 300,
                            OperationType = "Alquiler",
                            PropertyType = "Casa",
                            Rooms = 6
                        },
                        new
                        {
                            Id = 8,
                            Age = 0,
                            Description = "Lote con servicios al día en barrio cerrado, seguridad 24h.",
                            LocationCoordinates = "-34.386480564005815, -58.70008852211937",
                            M2 = 450,
                            OperationType = "Venta",
                            PropertyType = "Terreno",
                            Rooms = 0
                        },
                        new
                        {
                            Id = 9,
                            Age = 8,
                            Description = "Espacio de coworking flexible en Belgrano, incluye todos los servicios.",
                            LocationCoordinates = "-34.55660331473092, -58.449894494381375",
                            M2 = 90,
                            OperationType = "Alquiler",
                            PropertyType = "Oficina",
                            Rooms = 4
                        },
                        new
                        {
                            Id = 10,
                            Age = 50,
                            Description = "PH antiguo reciclado con terraza privada en San Telmo.",
                            LocationCoordinates = "-34.625080194090806, -58.37073447943592",
                            M2 = 120,
                            OperationType = "Venta",
                            PropertyType = "Departamento",
                            Rooms = 3
                        });
                });

            modelBuilder.Entity("Publicacion.Domain.Entities.Image", b =>
                {
                    b.HasOne("Publicacion.Domain.Entities.Publication", "Publication")
                        .WithMany("Images")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("Publicacion.Domain.Entities.Publication", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
