// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Publicacion.Infrastructure.Persistence;

#nullable disable

namespace Publicacion.Infrastructure.Migrations
{
    [DbContext(typeof(PublicationContext))]
    partial class PublicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Publicacion.Domain.Entities.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("LocationCoordinates")
                        .HasColumnType("text");

                    b.Property<int>("M2")
                        .HasColumnType("integer");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Rooms")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Publications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 15,
                            Description = "Casa con jardin y pileta, ideal para familia.",
                            LocationCoordinates = "-34.57073690807198, -58.41713926905615",
                            M2 = 140,
                            OperationType = "Venta",
                            PropertyType = "Casa",
                            Rooms = 4
                        },
                        new
                        {
                            Id = 2,
                            Age = 20,
                            Description = "Departamento de dos ambientes en Villa Crespo",
                            LocationCoordinates = "-34.5912740626822, -58.44926342405723",
                            M2 = 35,
                            OperationType = "Alquiler",
                            PropertyType = "Departamento",
                            Rooms = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
